# Generated by Django 3.2.7 on 2021-09-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210908_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Дате последней редакции поста', verbose_name='Дата последней редакции поста'),
        ),
    ]
