name: Django and Pytest CI
on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - "ubuntu-latest"
                    - "macos-latest"
                python-version:
                    - "3.8"
                    - "3.9"
                    - "3.10"
        name: Python ${{ matrix.python-version }} build on ${{ matrix.os }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Set up python
              id: setup-python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true
            - name: Load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v2
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
            - name: Install dependencies
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
              run: poetry install --no-interaction --no-root
            - name: Install library
              run: poetry install --no-interaction
            - name: Config .env
              run: |
                  mv backend/diafilm/dev.env backend/diafilm/.env
            - name: Run Django migrations
              run: |
                  source .venv/bin/activate
                  cd backend
                  python manage.py makemigrations
                  python manage.py migrate
            # - name: Run Film-scrape script
            #   run: |
            #       source .venv/bin/activate
            #       cd backend
            #       python manage.py film_scrape -t
            # - name: Run Django Tests
            #   run: |
            #       source .venv/bin/activate
            #       cd backend
            #       python manage.py test
            - name: Run flake8
              run: |
                  source .venv/bin/activate
                  flake8 backend --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics --config=backend/setup.cfg
