# Generated by Django 2.2.16 on 2021-09-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diafilms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
