# Generated by Django 3.2.7 on 2021-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafilms', '0002_auto_20210907_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-id',), 'verbose_name': 'Диафильм', 'verbose_name_plural': 'Диафильмы'},
        ),
        migrations.AlterField(
            model_name='filmcover',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
